name: Desativar reservas

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  comentar-linhas:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Comentar linhas
        run: |

          sed -i "s#await saveReserva(reserva);#// await saveReserva(reserva);#g" reservas/index.html

          sed -i "s#addMessage('✅ Reserva confirmada!');#/*addMessage('✅ Reserva confirmada!');*/#g" reservas/index.html

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add reservas/index.html

          git diff --cached --quiet || git commit -m "Desativa salvamento de reservas"

          git push
